### ISSUE TITLE
Licence

### ISSUE THREAD

**Issue by smutch** [phytest-devs/phytest#1]
We need to choose a license. I normally go with GNU GPLv3, but if we think that there may eventually be interest from commercial entities to contribute and use the code then I suppose MIT or Apache would be better...

See https://choosealicense.com .

**Comment by nfaux** [comment]
My preference is GNU GPLv3. It does not prohibit commercial use.

**Comment by smutch** [comment]
You're definitely right. I think the general preference for MIT when it comes to commercial stuff is the GPL condition that you have to disclose the source which prevents some companies from using it in their closed source proprietary software even if they are perfectly willing to upstream any changes they make. It's not something I've ever needed to consider with astro research code, but I really don't know the landscape here. :)

**Comment by Wytamma** [comment]
There is a large commercial side to bioinformatics so it might be worth going with a more general licence. It would be a nicer world if everything was open source, but I could definitely see this being used in commercial spaces. For example, The Microbiological Diagnostic Unit at the PDI offers phylogenetic analysis as a service and I don't think their full pipeline is open (or at least I can't find it in their github).

**Comment by smutch** [comment]
Vote time. :) Please thumb up if you are happy with MIT and I'll add that.
