### ISSUE TITLE
pre-commit.ci failing - poetry lock

### ISSUE THREAD

**Issue by Wytamma** [phytest-devs/phytest#22]
The pre-commit.ci action is failing because of the poetry lock hook.

https://results.pre-commit.ci/latest/github/phytest-devs/phytest/main

HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /pypi/openpyxl/json (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fc35c2adfa0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))

**Comment by smutch** [comment]
Doh! Sorry about that. I'm not sure if this is a temporary issue with the precommit CI service but, until we know more, I will disable this during CI as soon as I can get in front of a computer.

**Comment by Wytamma** [comment]
No worries! not a major issue, just flagging it.

**Comment by smutch** [comment]
Closed by #23
