### ISSUE TITLE
Repo permission

### ISSUE THREAD

**Issue by Wytamma** [phytest-devs/phytest#4]
I didn’t realise that you can’t have multiple owners on a personal repo i.e. collaborators can’t edit secrets etc. can we move the repo to an organisation so we can all be owners?

**Comment by smutch** [comment]
Absolutely. I didn't realise that either to be honest. I'll transfer to an organisation as soon as I get a chance in the next few days.

**Comment by Wytamma** [comment]
Sweet! no rush :)

**Comment by smutch** [comment]
Closed by transfer of repo to the new phytest-devs organisation.
