### ISSUE TITLE
Subclass the Bio python objects and add the asserts as methods

### ISSUE THREAD

**Issue by Wytamma** [phytest-devs/phytest#7]
There is at lot of repetition with the current interface. 

```python
from phytest import Sequence, asserts

def test_length(sequence: Sequence):
    asserts.sequences.assert_sequence_length(sequence, length=100)
```

I propose we subclass the biopython Alignment, Sequence, and Tree objects and add the asserts as methods to get this interface:

```python
from phytest import Sequence

def test_length(sequence: Sequence):
    sequence.assert_sequence_length(length=100)
```

**Comment by smutch** [comment]
Would we also be able to use `assert_length` instead of `assert_sequence_length` where appropriate with this approach?

**Comment by Wytamma** [comment]
Yeah definitely! That’d cut it down even more. I’ll start a branch for this 🚀
